### ISSUE TITLE
[BACK] Tags de solução

### ISSUE THREAD

**Issue by JoaoM-py** [The-Bugger-Ducks/help-duck-solution-center#3]
[SOLUÇÃO - CHAMADO]:
Quando o chamado for fechado será possível adicionar uma tag de solução.

- [x] Criar lógica das tags de solução.   

---
#### Definition of Done
- [x] Documentação
- [x] Verificar funcionamento (atender as expectativas para tarefa)
- [x] Code Review (abertura e aprovação de PR)
- [x] Validação do cliente (caso necessário)

**Comment by ThHenrique** [comment]
# Método para receber uma nova solução e incrementar a lista de solução de um problema

URL: ```<URL-SOLUTION>```/problems/update/idProblem

Payload: 

```js
{
	"title": "Troca para GatoNet",
	"description": "sla"
}
```
